### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by XavierB91**

### CODE REVIEW

**Review by elysemontano — CHANGES_REQUESTED** [review]
Indentation needs some attention in Apartment show.  Just a side note, try to make sure your commit messages communicate intent of the changes that you have made since your previous commit.  Initial commit should be a commit message reserved for only the first commit message you submit.

**Review by XavierB91 — COMMENTED** [review]
Committing show page : adding Link from Index to show, Display information of apartment, Link back to index, Styling, and Testing .

**Review by XavierB91 — COMMENTED** [review]
Fixed Indentation

**Comment by csaument** [comment]
Addressed merge conflict via mob - accepted updates to .scss and merged updates to the routing in App.js.

**Review by elysemontano — CHANGES_REQUESTED** [review]
What are you asserting in your test?  You should be checking in your test that specific information is there on the page.

**Comment by csaument** [comment]
Updated test to confirm rendering of the component and that the component contains an image, a heading, a next button, a previous button, and a link back to the index.

**Pull request merged**
